version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore: # Ignore some dependencies that are only used for development
      - dependency-name: "org.projectlombok:lombok"
      - dependency-name: "com.diffplug.spotless:spotless-maven-plugin"
    groups: # Group so it can create a single PR for all dependencies
      security-updates: # Group name for security updates
        applies-to: security-updates
        patterns:
          - "*"
    assignees:
      - "AadiManchekar"