---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: detect-aws-credentials
  - id: detect-private-key
- repo: https://github.com/pre-commit/sync-pre-commit-deps
  rev: v0.0.3
  hooks:
  - id: sync-pre-commit-deps
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
  - id: gitleaks
- repo: https://github.com/bufbuild/buf
  rev: v1.50.0
  hooks:
  - id: buf-format
