---
server:
  port: 9426
spring:
  application:
    name: dummy-child-module
  config:
    import: vault://
  cloud:
    vault:
      uri: http://vault:8201
      token: 00000000-0000-0000-0000-000000000000
      kv:
        enabled: true
        backend: secret
  kafka:
    bootstrap-servers: PLAINTEXT://kafka:9092
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  health:
    vault:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
