---
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-0
    ports:
    - 2181:2181
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-0
    ports:
    - 9092:9092
    healthcheck:
      test: kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit
        1
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
    - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
    - 7080:8080
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://localhost:8080/actuator/health | grep -q '"status":"UP"'
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      KAFKA_CLUSTERS_0_NAME: fleet-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
  vault:
    image: hashicorp/vault:1.19
    container_name: vault-0
    ports:
    - 8201:8201
    healthcheck:
      test:
      - CMD
      - vault
      - status
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure:10
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 00000000-0000-0000-0000-000000000000
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8201
      VAULT_ADDR: http://127.0.0.1:8201
      VAULT_LOCAL_CONFIG: |
        {
          "ui": true,
          "listener": {
            "tcp": {
              "tls_disable": true
            }
          },
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
        }
    cap_add:
    - IPC_LOCK
    command:
    - /bin/sh
    - -c
    - chmod +x /vault/init-vault.sh && /vault/init-vault.sh
    volumes:
    - vault-data:/vault/file
    - ./vault/init-vault.sh:/vault/init-vault.sh
  zipkin:
    image: openzipkin/zipkin:3.5
    container_name: zipkin
    ports:
    - 9411:9411
volumes:
  vault-data: null
