---
services:
  dummy-child-module:
    image: fleet/dummy-child-modul
    container_name: dummy-child-module
    ports:
    - 9426:9426
    depends_on:
      kafka:
        condition: service_healthy
      vault:
        condition: service_healthy
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    container_name: zookeeper-0
    ports:
    - 2181:2181
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:7.9.1
    container_name: kafka-0
    ports:
    - 9092:9092
    healthcheck:
      test:
      - CMD
      - kafka-topics
      - --bootstrap-server
      - kafka:9092
      - --list
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    depends_on:
      zookeeper:
        condition: service_healthy
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
    - 7080:8080
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://localhost:8080/actuator/health | grep -q '"status":"UP"'
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      KAFKA_CLUSTERS_0_NAME: fleet-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
  vault:
    image: hashicorp/vault:1.19
    container_name: vault-0
    ports:
    - 8201:8201
    healthcheck:
      test:
      - CMD
      - vault
      - status
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure:10
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 00000000-0000-0000-0000-000000000000
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8201
      VAULT_ADDR: http://vault:8201
      VAULT_LOCAL_CONFIG: |
        {
          "ui": true,
          "listener": {
            "tcp": {
              "tls_disable": true
            }
          }
        }
    cap_add:
    - IPC_LOCK
    command:
    - /bin/sh
    - -c
    - chmod +x /vault/init-vault.sh && /vault/init-vault.sh
    volumes:
    - ./vault/init-vault.sh:/vault/init-vault.sh
  zipkin:
    image: openzipkin/zipkin:3.5
    container_name: zipkin
    ports:
    - 9411:9411
volumes:
  vault-data: null
