---
name: Fleet CI
"on":
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
      packages: write
    strategy:
      matrix:
        java-version:
        - 17
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: maven
    - name: Resolve Maven Dependencies and Plugins
      run: mvn dependency:resolve dependency:resolve-plugins
    - name: Check formatting with Spotless
      run: mvn spotless:check
    - name: Spin up Docker Compose
      continue-on-error: false
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: ./tools/docker/docker-compose.yaml
    - name: Compile and Test
      run: |
        cd tools/build
        chmod +x ./compile.sh
        ./compile.sh
